name: Deploy Website on Commit

on:
  push:
    branches:
      - dev
    paths:
      - 'website/**'  # Only trigger when changes occur in the website folder

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.15.0' 

    - name: Install dependencies
      run: npm ci
      working-directory: ./website  # Navigate to the website folder

    - name: Build the project
      run: npm run build
      working-directory: ./website

    - name: Add CNAME file
      run: echo 'teamcommtools.seas.upenn.edu' > ./website/build/CNAME

    - name: Configure Git
      run: |
        git config --global user.email "team_comm_tools_admin@gmail.com"
        git config --global user.name "team_comm_tools_admin"
      working-directory: ./website
      
    - name: Deploy
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        npm run deploy
      working-directory: ./website  # Run deploy inside the website folder
