name: Deploy Website on Commit

on:
  push:
    branches:
      - amy/website
    paths:
      - 'website/**'  # Only trigger when changes occur in the website folder

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16.x'  # You can adjust this to your preferred Node.js version

    - name: Install dependencies
      run: npm ci
      working-directory: ./website  # Navigate to the website folder

    - name: Deploy
      run: npm run deploy
      working-directory: ./website  # Run deploy inside the website folder